#!/usr/bin/python3

from os import getenv

storage = getenv("HBNB_TYPE_STORAGE")

if storage == "db":
    from model.engine.db_storage import DBStorage
    storage = DBStorage()

else:
    from model.engine.file_storage import FileStorage
    storage = FileStorage()

    storage.reload()

